# Generated by Django 3.2.16 on 2023-05-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField()),
                ('staff_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor')], default='Admin', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=100, verbose_name='Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='Main.profile')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='mental_illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_illness_name', models.CharField(max_length=150, verbose_name='Mental Illness Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('symptoms', models.ManyToManyField(related_name='mental_illnesses', to='Main.symptom')),
            ],
            options={
                'verbose_name_plural': 'Mental Illness',
            },
        ),
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name="Patient's Name")),
                ('lastname', models.CharField(max_length=30, verbose_name="Patient's Surname")),
                ('patient_number', models.CharField(max_length=20, verbose_name="Patient's Number")),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mental_illness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mental_illness', to='Main.mental_illness')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(related_name='diagnoses', to='Main.symptom')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis',
            },
        ),
    ]
